# Generated by Django 5.1.2 on 2024-11-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cover', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coverpage',
            old_name='coruseName',
            new_name='coruse_code',
        ),
        migrations.RenameField(
            model_name='coverpage',
            old_name='name',
            new_name='sname',
        ),
        migrations.AddField(
            model_name='coverpage',
            name='session',
            field=models.CharField(default='DefaultSession', max_length=10),
        ),
    ]
